version: '1.0'
mode: parallel
stages:
- lint
- prep
- test

steps:
  lint:
    title: Run format linting
    stage: lint
    image: unibeautify/clang-format:latest
    working_directory: ${{main_clone}}
    entrypoint: bash
    commands:
    - -|
      find include/ src/ -type f \( -iname *.h -o -iname *.cpp \) -print0 | \
        xargs -0 -I {} bash -c 'if [[ $(clang-format-7 {} | diff - {}) ]]; then (echo {}; exit 1); else (exit 0); fi'
    when:
      steps:
      - name: main_clone
        on:
        - success

  build_test:
    type: build
    stage: test
    title: Build test image
    dockerfile: Dockerfile-test
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: test
    when:
      steps:
      - name: main_clone
        on:
        - success

  gcc-7-prep: &prep
    type: build
    stage: prep
    title: Prep test image
    dockerfile: Dockerfile-build
    build_arguments:
    - GCC_VERSION=7
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    when:
      steps:
      - name: main_clone
        on:
        - success

  gcc-7: &test
    title: Run test
    stage: test
    image: gcc:7
    working_directory: ${{main_clone}}
    commands:
    - BUILDS=(Debug Release)
    - mkdir build
    - pushd build
    - |-
      for BUILD in "${BUILDS[@]}"; do
        (
          set -x
          cmake -DCMAKE_BUILD_TYPE="${BUILD}"              \
                -DCMAKE_INSTALL_PREFIX:PATH=install        \
                -DSPDLOG_SETUP_INCLUDE_UNIT_TESTS=ON ..
        )

        cmake --build . --target install
        ctest -R spdlog_setup_unit_test -V
        ec=$?

        (exit $ec)
      done
    - popd
    when:
      steps:
      - name: gcc-7-prep
        on:
        - success
