version: '1.0'
mode: parallel
stages:
- prep
- lint
- test

steps:
  lint-prep:
    type: build
    stage: prep
    title: Prep lint image
    dockerfile: Dockerfile-lint
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}-lint
    when:
      steps:
      - name: main_clone
        on:
        - success

  gcc-8-prep: &prep
    type: build
    stage: prep
    title: Prep test image gcc-8
    dockerfile: Dockerfile-build
    build_arguments:
    - GCC_VERSION=8
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}-test
    when:
      steps:
      - name: main_clone
        on:
        - success

  gcc-7-prep:
    <<: *prep
    title: Prep test image gcc-7
    build_arguments:
    - GCC_VERSION=7

  lint:
    title: Run format linting
    stage: lint
    image: ${{lint-prep}}
    working_directory: ${{main_clone}}
    entrypoint: bash
    commands:
    - |-
      find include/ src/ -type f \( -iname *.h -o -iname *.cpp \) -print0 | \
        xargs -0 -I {} bash -c 'if [[ $(clang-format {} | diff - {}) ]]; then (echo {}; exit 1); else (exit 0); fi'
    when:
      steps:
      - name: lint-prep
        on:
        - success

  gcc-8: &test
    title: Run test gcc-8
    stage: test
    image: gcc:8
    working_directory: ${{main_clone}}
    commands:
    - mkdir -p build
    - pushd build
    - |-
      for BUILD in "Debug Release"; do
        (
          set -x
          cmake -DCMAKE_BUILD_TYPE="${BUILD}"              \
                -DCMAKE_INSTALL_PREFIX:PATH=install        \
                -DSPDLOG_SETUP_INCLUDE_UNIT_TESTS=ON ..
        )

        cmake --build . --target install
        ctest -R spdlog_setup_unit_test -V
        ec=$?

        (exit $ec)
      done
    - popd
    when:
      steps:
      - name: gcc-8-prep
        on:
        - success

  gcc-7:
    <<: *test
    title: Run test gcc-7
    image: gcc:7
    when:
      steps:
      - name: gcc-7-prep
        on:
        - success
