# level is optional for both sinks and loggers
# level for error logging is 'err', not 'error'

# max_size supports suffix
# - T (terabyte)
# - G (gigabyte)
# - M (megabyte)
# - K (kilobyte)
# - or simply no suffix (byte)

[[sink]]
name = "console"
type = "stdout_sink_mt"

[[sink]]
name = "simple_out"
type = "simple_file_sink_mt"
filename = "log/simple-{index}-{path}.log"
truncate = false
level = "info"

[[sink]]
name = "simple_err"
type = "simple_file_sink_mt"
filename = "log/simple-{index}-{path}_err.log"
truncate = false
level = "err"

[[logger]]
name = "root"
sinks = ["console", "simple_out", "simple_err"]
level = "trace"
